name: client-build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

defaults:
  run:
    working-directory: client

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run electron:build:win
          - os: macos-latest
            build_cmd: npm run electron:build:mac
          - os: ubuntu-latest
            build_cmd: npm run electron:build:linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build & package
        run: ${{ matrix.build_cmd }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: entrocut-${{ runner.os }}
          path: client/release/**/*
